import crypto from "node:crypto";
const BASE="https://auth.uber.com";
const SUPABASE_URL=process.env.VITE_SUPABASE_URL||"https://skfxzagxlxputwpwxwbe.supabase.co";
const SUPABASE_KEY=process.env.SUPABASE_SECRET_KEY;
const CLIENT_ID=process.env.UBER_CLIENT_ID;
const CLIENT_SECRET=process.env.UBER_CLIENT_SECRET;
const REDIRECT_URI="https://tryfetch.in/api/fetch/uber/callback.mjs";
const clean=v=>String(v??"").trim();
async function db(path,options={}){if(!SUPABASE_KEY)throw new Error("SUPABASE_SECRET_KEY is missing");const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json",...(options.headers||{})}});const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw new Error("Supabase "+r.status+": "+(typeof d==="string"?d:JSON.stringify(d)));return d}
function requireConfig(){if(!CLIENT_ID)throw new Error("UBER_CLIENT_ID is missing");if(!CLIENT_SECRET)throw new Error("UBER_CLIENT_SECRET is missing")}
export async function beginUberAuth(conversationId){requireConfig();const state=crypto.randomBytes(32).toString("base64url");await db("fetch_provider_oauth_states",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({state,conversation_id:clean(conversationId),provider_id:"uber",client_id:CLIENT_ID,redirect_uri:REDIRECT_URI,expires_at:new Date(Date.now()+600000).toISOString()})});const u=new URL(BASE+"/oauth/v2/authorize");u.searchParams.set("response_type","code");u.searchParams.set("client_id",CLIENT_ID);u.searchParams.set("redirect_uri",REDIRECT_URI);u.searchParams.set("scope","profile request offline_access");u.searchParams.set("state",state);return u.toString()}
export async function consumeUberState(state){const rows=await db("fetch_provider_oauth_states?state=eq."+encodeURIComponent(clean(state))+"&provider_id=eq.uber&select=*&limit=1");const row=Array.isArray(rows)&&rows.length?rows[0]:null;if(!row)return null;await db("fetch_provider_oauth_states?state=eq."+encodeURIComponent(clean(state))+"&provider_id=eq.uber",{method:"DELETE"});if(new Date(row.expires_at).getTime()<Date.now())return null;return row}
export async function exchangeUberCode(row,code){requireConfig();const form=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:"authorization_code",redirect_uri:REDIRECT_URI,code:clean(code)});const r=await fetch(BASE+"/oauth/v2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:form.toString()});const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null}catch{d={raw}}if(!r.ok||!d?.access_token)throw new Error(d?.error_description||d?.error||"Uber token exchange failed (HTTP "+r.status+")");return d}
export async function saveUberToken(conversationId,token){const expiresIn=Math.max(60,Number(token.expires_in||2592000));const expiresAt=new Date(Date.now()+expiresIn*1000).toISOString();await db("fetch_provider_connections?conversation_id=eq."+encodeURIComponent(clean(conversationId))+"&provider_id=eq.uber",{method:"DELETE"});await db("fetch_provider_connections",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({conversation_id:clean(conversationId),provider_id:"uber",access_token:clean(token.access_token),refresh_token:clean(token.refresh_token),token_type:clean(token.token_type)||"Bearer",scopes:clean(token.scope).split(/\s+/).filter(Boolean),expires_at:expiresAt})});return expiresAt}
export async function getUberToken(conversationId){const rows=await db("fetch_provider_connections?conversation_id=eq."+encodeURIComponent(clean(conversationId))+"&provider_id=eq.uber&select=access_token,refresh_token,token_type,scopes,expires_at&limit=1");const row=Array.isArray(rows)&&rows.length?rows[0]:null;if(!row||new Date(row.expires_at).getTime()<=Date.now()+60000)return null;return row}
export async function uberRequest({accessToken,path,method="GET",body=null}={}){if(!clean(accessToken))throw new Error("Uber connection is required");const r=await fetch("https://api.uber.com/v1.2"+path,{method,headers:{Authorization:"Bearer "+accessToken,"Content-Type":"application/json",Accept:"application/json"},...(body?{body:JSON.stringify(body)}:{})});const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw new Error("Uber API "+r.status+": "+(typeof d==="string"?d:JSON.stringify(d)));return d}